services:
  sec-api:
    image: "sec-api"
    build: .
    container_name: sec-api
    ports:
      - "55555:8080"
    volumes:
      - C:\Users\SECMEGA\Desktop\Project\sec_api\file-server:/file-server/
    networks:
      - sec_net
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: sec_db
    image: postgres:17.4-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_VOL}:/var/lib/postgresql/data
    networks:
      - sec_net

volumes:
  postgresql_data:
    driver: local
networks:
  sec_net:
    driver: bridge
