spring.application.name=secApi
server.port=16800
spring.profiles.active=dev

#config file size
logging.logback.rollingpolicy.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB

#swagger config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true