spring.application.name=secApi
server.port=16800
spring.profiles.active=dev

#config file size
logging.logback.rollingpolicy.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#swagger config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#bunny storage
bunny.storage-zone=sec-mega-storage
bunny.api-key=9a0b8880-a1d0-4a61-90f9ac5293bf-cf15-472b
bunny.cdn-url=https://sec-pull-zone.b-cdn.net
bunny.region=