spring.application.name=secApi
# Server Config
server.port=16800
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html
server.compression.min-response-size=1024

# Thread config
spring.threads.virtual.enabled=true

# profile config
spring.profiles.active=dev

#config file size
logging.logback.rollingpolicy.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#swagger config
    springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#cloudflare r2 bucket
cloudflare.r2.bucket=sec-storage-001
cloudflare.r2.public-url=https://cdn.sec-mega.site
cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY:access_key}
cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY:secret_key}
cloudflare.r2.endpoint=https://3dc90edd93b0d5514c48f0ba9f794204.r2.cloudflarestorage.com

app.security.access-token.private-key=classpath:keys/access_private_pkcs8.pem
app.security.access-token.public-key=classpath:keys/access_public.pem
app.security.refresh-token.private-key=classpath:keys/refresh_private_pkcs8.pem
app.security.refresh-token.public-key=classpath:keys/refresh_public.pem

# Report File
materialExcel.template.path=/jasper/materialExcel.jasper
materialStockInExcel.template.path=/jasper/materialStockInExcel.jasper
materialStockOutExcel.template.path=/jasper/materialStockOutExcel.jasper

# Database optimize
#spring.jpa.properties.hibernate.default_batch_fetch_size=20
#spring.jpa.open-in-view=false