# postgres database properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sec_db
spring.datasource.username=eichanudom
spring.datasource.password=Domkh@#12

# hibernate properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# file properties
file-server.server-path=C:\\Users\\SECMEGA\\Desktop\\SEC_WEB\\sec_backend\\file-server\\

