# postgres database properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db:5432/sec_db
spring.datasource.username=eichanudom
spring.datasource.password=Domkh@#12

# hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# file properties
file-server.base-uri=https://api.sec-mega.site/files/
file-server.server-path = /file-server/